# Generated by Django 5.0.6 on 2024-07-03 19:53

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCat', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEtiqueta', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priNomAutor', models.CharField(max_length=15)),
                ('segNomAutor', models.CharField(max_length=15)),
                ('apPaternoAutor', models.CharField(max_length=15)),
                ('apMaternoAutor', models.CharField(max_length=15)),
                ('fonoAutor', models.CharField(max_length=11)),
                ('correoElectronico', models.CharField(default='example@email.com', max_length=40)),
                ('usuarioAutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='autor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priNomEditor', models.CharField(max_length=15)),
                ('segNomEditor', models.CharField(max_length=15)),
                ('apPaternoEditor', models.CharField(max_length=15)),
                ('apMaternoEditor', models.CharField(max_length=15)),
                ('fonoEditor', models.CharField(max_length=11)),
                ('correoElectronico', models.CharField(default='example@email.com', max_length=40)),
                ('usuarioEditor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloArticulo', models.CharField(max_length=255)),
                ('etiquetaTitulo', models.CharField(default='Noticias Caos', max_length=255)),
                ('contenidoArticulo', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('sinopsisArticulo', models.CharField(max_length=255)),
                ('imagenArticulo', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('fechaPublicacion', models.DateField(auto_now_add=True)),
                ('usuarioAutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos_autor', to='SitioWebNoticiasCaos.autor')),
                ('nombreCat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SitioWebNoticiasCaos.categoria')),
                ('usuarioEditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articulos_editor', to='SitioWebNoticiasCaos.editor')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePerfil', models.CharField(max_length=40)),
                ('usuarioPagina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
