# Generated by Django 5.0.6 on 2024-06-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SitioWebNoticiasCaos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='etiquetaTitulo',
            field=models.CharField(default='Noticias Caos', max_length=255),
        ),
        migrations.AddField(
            model_name='autor',
            name='correoElectronico',
            field=models.CharField(default='example@email.com', max_length=40),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='tituloArticulo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='nombreEtiqueta',
            field=models.CharField(max_length=40),
        ),
    ]
