# Generated by Django 5.0.6 on 2024-07-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SitioWebNoticiasCaos', '0002_alter_autor_usuarioautor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='nombreCat',
            field=models.CharField(default='Sin Asignar', max_length=255),
        ),
    ]
