# Generated by Django 5.0.6 on 2024-06-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SitioWebNoticiasCaos', '0003_articulo_fechapublicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagenArticulo',
            field=models.ImageField(blank=True, null=True, upload_to='SitioWebNoticiasCaos/img/'),
        ),
    ]
