# Generated by Django 5.0.6 on 2024-07-03 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SitioWebNoticiasCaos', '0003_alter_articulo_nombrecat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='usuarioEditor',
        ),
        migrations.DeleteModel(
            name='Editor',
        ),
    ]
