# Generated by Django 5.0.6 on 2024-06-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SitioWebNoticiasCaos', '0004_alter_articulo_imagenarticulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='sinopsisArticulo',
            field=models.CharField(default=' Click en el articulo para leer', max_length=255),
        ),
    ]
