# Generated by Django 5.0.6 on 2024-07-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SitioWebNoticiasCaos', '0005_remove_articulo_nombrecat_editor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='nombreCat',
            field=models.CharField(default='Sin Asignar', max_length=255),
        ),
    ]
