# Generated by Django 5.0.6 on 2024-06-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SitioWebNoticiasCaos', '0005_articulo_sinopsisarticulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagenArticulo',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='sinopsisArticulo',
            field=models.CharField(max_length=255),
        ),
    ]
