# Generated by Django 5.0.6 on 2024-07-03 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SitioWebNoticiasCaos', '0006_articulo_nombrecat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='nombreCat',
        ),
    ]
