# Generated by Django 5.0.6 on 2024-07-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SitioWebNoticiasCaos', '0007_remove_articulo_nombrecat'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='nombreCat',
            field=models.CharField(default='Sin Asignar', max_length=255),
        ),
    ]
